import { CollegeAdmission } from './types';

export const ADMISSIONS_DATA: CollegeAdmission[] = [
  { id: '1', admissionGrade: 6.38, university: '전남대학교(여수)', selectionType: '학생부교과', detailType: '학생부교과(일반)', department: '해양수산광역', admissionType: '충원합격' },
  { id: '2', admissionGrade: 5.72, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '공학분야', admissionType: '충원합격' },
  { id: '3', admissionGrade: 5.13, university: '국립순천대학교', selectionType: '학생부종합', detailType: '학생부종합(일반학생전형)', department: '건축학부', admissionType: '합격' },
  { id: '4', admissionGrade: 5.13, university: '원광대학교', selectionType: '학생부종합', detailType: '학생부종합(지역인재종합전형)(호남권)', department: '건축학과', admissionType: '합격' },
  { id: '5', admissionGrade: 5.13, university: '전주대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생전형)', department: '건축학과', admissionType: '충원합격' },
  { id: '6', admissionGrade: 6.16, university: '김천대학교', selectionType: '학생부교과', detailType: '학생부교과(일반면접전형)', department: '간호학과', admissionType: '충원합격' },
  { id: '7', admissionGrade: 6.16, university: '송원대학교', selectionType: '학생부교과', detailType: '학생부교과(인성우수자-일반전형)', department: '간호학과', admissionType: '충원합격' },
  { id: '8', admissionGrade: 3.22, university: '전남대학교', selectionType: '학생부교과', detailType: '학생부교과(일반)', department: '기계공학부', admissionType: '충원합격' },
  { id: '9', admissionGrade: 3.22, university: '전남대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재)', department: '기계공학부', admissionType: '충원합격' },
  { id: '10', admissionGrade: 3.22, university: '전북대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생 전형)', department: '공학계열1', admissionType: '합격' },
  { id: '11', admissionGrade: 6.76, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '공학분야', admissionType: '충원합격' },
  { id: '12', admissionGrade: 4.27, university: '동아대학교', selectionType: '학생부교과', detailType: '학생부교과(교과성적우수자전형)', department: '전기공학과', admissionType: '합격' },
  { id: '13', admissionGrade: 4.27, university: '울산대학교', selectionType: '학생부교과', detailType: '학생부교과(일반교과 전형)', department: '전기전자융합학부', admissionType: '충원합격' },
  { id: '14', admissionGrade: 5.09, university: '원광대학교', selectionType: '학생부교과', detailType: '학생부교과(일반전형)', department: '공학2계열', admissionType: '합격' },
  { id: '15', admissionGrade: 5.09, university: '조선대학교', selectionType: '학생부교과', detailType: '학생부교과(일반전형)', department: '항공우주공학과', admissionType: '충원합격' },
  { id: '16', admissionGrade: 5.09, university: '조선대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '전자공학과', admissionType: '충원합격' },
  { id: '17', admissionGrade: 5.25, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '공학분야', admissionType: '충원합격' },
  { id: '18', admissionGrade: 5.25, university: '조선대학교', selectionType: '학생부교과', detailType: '학생부교과(일반전형)', department: '전자공학과', admissionType: '충원합격' },
  { id: '19', admissionGrade: 6.65, university: '청주대학교', selectionType: '실기전형', detailType: '실기/실적위주(예체능전형)', department: '영화영상학과', admissionType: '합격' },
  { id: '20', admissionGrade: 6.65, university: '한국영상대학교', selectionType: '학생부교과', detailType: '일반전형', department: '영상편집제작학과', admissionType: '합격' },
  { id: '21', admissionGrade: 4.78, university: '국립목포대학교', selectionType: '학생부교과', detailType: '학생부교과(교과일반전형)', department: '자율전공학부', admissionType: '충원합격' },
  { id: '22', admissionGrade: 4.78, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '공학분야', admissionType: '충원합격' },
  { id: '23', admissionGrade: 3.22, university: '전남대학교(여수)', selectionType: '학생부교과', detailType: '학생부교과(지역인재)', department: '수산생명의학과', admissionType: '합격' },
  { id: '24', admissionGrade: 3.04, university: '전남대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재)', department: '기계공학부', admissionType: '충원합격' },
  { id: '25', admissionGrade: 3.04, university: '경기대학교(수원)', selectionType: '학생부교과', detailType: '학생부교과(교과성적우수자전형)', department: '기계시스템공학과', admissionType: '충원합격' },
  { id: '26', admissionGrade: 3.04, university: '상명대학교', selectionType: '학생부종합', detailType: '학생부종합(상명인재전형)', department: 'SW융합학부 전기공학전공', admissionType: '합격' },
  { id: '27', admissionGrade: 6.61, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(교과일반전형)', department: '생명산업과학분야', admissionType: '충원합격' },
  { id: '28', admissionGrade: 6.61, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '공학분야', admissionType: '충원합격' },
  { id: '29', admissionGrade: 5.4, university: '국립목포대학교', selectionType: '학생부교과', detailType: '학생부교과(교과일반전형)', department: '전기공학과', admissionType: '충원합격' },
  { id: '30', admissionGrade: 5.5, university: '송원대학교', selectionType: '학생부교과', detailType: '학생부교과(인성우수자-일반전형)', department: '간호학과', admissionType: '합격' },
  { id: '31', admissionGrade: 5.09, university: '조선대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '전자공학과', admissionType: '충원합격' },
  { id: '32', admissionGrade: 4.66, university: '조선대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '기계공학과', admissionType: '충원합격' },
  { id: '33', admissionGrade: 4.66, university: '경상국립대학교', selectionType: '학생부교과', detailType: '학생부교과(일반전형)', department: '신소재공학부 금속재료공학전공', admissionType: '충원합격' },
  { id: '34', admissionGrade: 4.66, university: '국립금오공과대학교', selectionType: '학생부교과', detailType: '학생부교과(학생부교과전형)', department: '기계공학부', admissionType: '충원합격' },
  { id: '35', admissionGrade: 5.44, university: '전남대학교(여수)', selectionType: '학생부교과', detailType: '학생부교과(일반)', department: '기관시스템공학과', admissionType: '충원합격' },
  { id: '36', admissionGrade: 5.44, university: '전남대학교(여수)', selectionType: '학생부교과', detailType: '학생부교과(지역인재)', department: '공학계열', admissionType: '합격' },
  { id: '37', admissionGrade: 3.84, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '공학분야', admissionType: '합격' },
  { id: '38', admissionGrade: 5.18, university: '국립목포대학교', selectionType: '학생부교과', detailType: '학생부교과(교과일반전형)', department: '수산생명의학과', admissionType: '충원합격' },
  { id: '39', admissionGrade: 5.18, university: '국립목포대학교', selectionType: '학생부종합', detailType: '학생부종합(종합일반전형)', department: '수산생명의학과', admissionType: '충원합격' },
  { id: '40', admissionGrade: 5.18, university: '조선대학교', selectionType: '학생부교과', detailType: '학생부교과(일반전형)', department: '기계공학과', admissionType: '합격' },
  { id: '41', admissionGrade: 5.18, university: '전남대학교(여수)', selectionType: '학생부교과', detailType: '학생부교과(일반)', department: '해양수산광역', admissionType: '충원합격' },
  { id: '42', admissionGrade: 5.18, university: '경상국립대학교', selectionType: '학생부교과', detailType: '학생부교과(일반전형)', department: '해양식품생명의학부', admissionType: '합격' },
  { id: '43', admissionGrade: 5.18, university: '국립공주대학교', selectionType: '학생부종합', detailType: '학생부종합(일반전형)', department: '수산생명의학과', admissionType: '충원합격' },
  { id: '44', admissionGrade: 2.99, university: '전남대학교', selectionType: '학생부교과', detailType: '학생부교과(일반)', department: '신소재공학부', admissionType: '충원합격' },
  { id: '45', admissionGrade: 2.99, university: '전남대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재)', department: '기계공학부', admissionType: '충원합격' },
  { id: '46', admissionGrade: 2.99, university: '전북대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생 전형)', department: '공학계열1', admissionType: '합격' },
  { id: '47', admissionGrade: 3.81, university: '전북대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생 전형)', department: '공학계열1', admissionType: '충원합격' },
  { id: '48', admissionGrade: 4.72, university: '경상국립대학교', selectionType: '학생부종합', detailType: '학생부종합(일반전형)', department: '컴퓨터공학부', admissionType: '충원합격' },
  { id: '49', admissionGrade: 4.72, university: '국립목포대학교', selectionType: '학생부교과', detailType: '학생부교과(교과일반전형)', department: '컴퓨터학부', admissionType: '합격' },
  { id: '50', admissionGrade: 4.72, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '공학분야', admissionType: '합격' },
  { id: '51', admissionGrade: 4.72, university: '국립한국교통대학교', selectionType: '학생부교과', detailType: '학생부교과(일반전형)', department: '컴퓨터공학과', admissionType: '충원합격' },
  { id: '52', admissionGrade: 5.88, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '공학분야', admissionType: '충원합격' },
  { id: '53', admissionGrade: 5.88, university: '전주대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생전형)', department: '전기전자공학과', admissionType: '충원합격' },
  { id: '54', admissionGrade: 5.88, university: '조선대학교', selectionType: '학생부교과', detailType: '학생부교과(일반전형)', department: '기계공학과', admissionType: '충원합격' },
  { id: '55', admissionGrade: 5.88, university: '원광대학교', selectionType: '학생부교과', detailType: '학생부교과(일반전형)', department: '공학2계열', admissionType: '충원합격' },
  { id: '56', admissionGrade: 5.84, university: '국립목포대학교', selectionType: '학생부교과', detailType: '학생부교과(교과일반전형)', department: '건축 ・ 토목 ・ 환경공학부', admissionType: '충원합격' },
  { id: '57', admissionGrade: 5.84, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(교과일반전형)', department: '공학분야', admissionType: '충원합격' },
  { id: '58', admissionGrade: 5.84, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '생명산업과학분야', admissionType: '충원합격' },
  { id: '59', admissionGrade: 4.4, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '공학분야', admissionType: '합격' },
  { id: '60', admissionGrade: 4.4, university: '국립한국교통대학교', selectionType: '학생부교과', detailType: '학생부교과(일반전형)', department: '전자공학과', admissionType: '충원합격' },
  { id: '61', admissionGrade: 8.8, university: '원광대학교', selectionType: '학생부교과', detailType: '학생부교과(일반전형)', department: '공학2계열', admissionType: '충원합격' },
  { id: '62', admissionGrade: 8.8, university: '전주대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생전형)', department: '기계자동차공학과', admissionType: '충원합격' },
  { id: '63', admissionGrade: 8.8, university: '광주대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생)', department: '기계자동차공학과', admissionType: '충원합격' },
  { id: '64', admissionGrade: 6.85, university: '동의대학교', selectionType: '학생부교과', detailType: '학생부교과(일반고교과전형)', department: '토목공학과', admissionType: '충원합격' },
  { id: '65', admissionGrade: 6.85, university: '전주대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생전형)', department: '건축공학과', admissionType: '충원합격' },
  { id: '66', admissionGrade: 6.77, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '공학분야', admissionType: '충원합격' },
  { id: '67', admissionGrade: 6.77, university: '전남대학교(여수)', selectionType: '학생부교과', detailType: '학생부교과(일반)', department: '공학계열', admissionType: '충원합격' },
  { id: '68', admissionGrade: 4.66, university: '국립금오공과대학교', selectionType: '학생부교과', detailType: '학생부교과(학생부교과전형)', department: '기계공학부', admissionType: '충원합격' },
  { id: '69', admissionGrade: 4.66, university: '전북대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형 1유형)', department: '첨단방위산업학과', admissionType: '충원합격' },
  { id: '70', admissionGrade: 6.79, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '공학분야', admissionType: '충원합격' },
  { id: '71', admissionGrade: 6.79, university: '호남대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생A전형)', department: 'e스포츠산업학과', admissionType: '합격' },
  { id: '72', admissionGrade: 6.67, university: '국립목포대학교', selectionType: '학생부교과', detailType: '학생부교과(교과일반전형)', department: '건축 ・ 토목 ・ 환경공학부', admissionType: '충원합격' },
  { id: '73', admissionGrade: 6.67, university: '국립순천대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재전형)', department: '공학분야', admissionType: '충원합격' },
  { id: '74', admissionGrade: 6.67, university: '전주대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생전형)', department: '기계공학과', admissionType: '충원합격' },
  { id: '75', admissionGrade: 4.41, university: '제주대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생 전형)', department: '해양생명과학과', admissionType: '합격' },
  { id: '76', admissionGrade: 3.18, university: '전남대학교', selectionType: '학생부교과', detailType: '학생부교과(일반)', department: '인공지능학부', admissionType: '충원합격' },
  { id: '77', admissionGrade: 3.18, university: '전남대학교', selectionType: '학생부종합', detailType: '학생부종합(고교생활우수자Ⅰ)', department: '전자컴퓨터공학부', admissionType: '합격' },
  { id: '78', admissionGrade: 2.74, university: '전남대학교', selectionType: '학생부교과', detailType: '학생부교과(지역인재)', department: '전자컴퓨터공학부', admissionType: '합격' },
  { id: '79', admissionGrade: 2.74, university: '한양대학교(ERICA)', selectionType: '학생부종합', detailType: '학생부종합(서류형)', department: '컴퓨터학부', admissionType: '충원합격' },
  { id: '80', admissionGrade: 2.74, university: '전북대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생 전형)', department: '공학계열1', admissionType: '합격' },
  { id: '81', admissionGrade: 6.05, university: '전주대학교', selectionType: '학생부교과', detailType: '학생부교과(일반학생전형)', department: '재활학과', admissionType: '충원합격' }
];
